apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: app2-dev
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
    destination:
        name: in-cluster
        namespace: app2-dev
    source:
        path: "HelmCharts/MyChart2"
        repoURL: "http://192.168.1.124/devops/argocd-one-cluster.git"
        targetRevision: HEAD
        helm:
            valueFiles:
                - values_dev.yaml
            parameters:
                - name: "container.image"
                  value: yenzedm/flask-test:1.0

    project: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            # allowEmpty: true
        syncOptions:
            - CreateNamespace=true
